Improve task authorized_keys
4eixos/role-base pull request #6
Opened 2022-10-13 21:01 UTC by gustavoborragan

Improve task so that it doesn't delete packer's ssh public key and fail connection after VM reboot

2022-10-13 21:25 UTC, alambike requested changes
@gustavoborragan sorry, but I don't understand the point of this change. This role is used to maintain a group of keys, from the public_keys folder of the working directory, to the authorized_keys file of the sudo user (ansible user). What are you trying to achieve? Maybe you could configure packer to use a fixed ssh key, and add the public part to the public_keys folder? Do you see the available options of the [ssh communicator](https://www.packer.io/docs/communicators/ssh#ssh-communicator-1)

2022-10-14 07:49 UTC, gustavoborragan commented
Maiby with this? ansible_ssh_private_key_file

https://www.packer.io/plugins/provisioners/ansible/ansible#ssh_authorized_key_file

2022-10-16 22:01 UTC, gustavoborragan commented
Desestimated!!!

2022-10-16 22:02 UTC, closed without merging

2022-10-17 10:24 UTC, alambike commented
@gustavoborragan were you finally able to configure a fixed key in packer?